Cuckoo Hashing
wongwill86/projectfoo pull request #2
Opened 2017-03-09 18:34 UTC by nkemnitz

Cuckoo Hashing for uint8, uint16, uint32, uint64 and float32 values -- although only tested with uint64
Three hashing functions are available: Identity, Murmur3 and FNV-1a.
By default it is using [Identity, FNV-1a]. Changing those requires modifications to the shader as well.

2017-03-09 18:53 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    this._texture = new BABYLON.Texture('', this._scene, true);
let's switch away from underscores, try to be more consistent with https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
(though we already agreed to use single quotes)

2017-03-09 21:16 UTC, wongwill86 requested changes

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +  private _lastInsertError: { lo: number, hi: number };
can we make `{ lo: number, hi: number }` a separate type? something like

allowing undefined seems to make more sense than the magical type of `{low:0, hi:0}`
`private lastInsertError : Int64 | undefined`

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    this._lastInsertError = { lo: 0, hi: 0 };
from above comment to use `undefined`

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +  private _setElements: number;
might be good to call this `elementsSet `or `elementCount` or something so we don't mistaken `setX` for being a setter function.
It'll be good to make this public so we can always know how many elements we have selected in this data structure.

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    pos = this._hashfunctions[1].compute(lo, hi) % this._sizes.maxsize;
This looks like duplicated code.
You can probably use something cool like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    pos = this._hashfunctions[1].compute(lo, hi) % this._sizes.maxsize;
same as before you can do something cool like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +      if (tmp.lo > 0 || tmp.hi > 0) {
great place to replace with `if (tmp !== undefined)`

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    let tmp = this.getLastInsertError();
why not put this as an input to the function?

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    let tmp = this.getLastInsertError();
looks like it's because we always have a random value that may not be indexed when rehashing and this function modifies the buffer in place.

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +    let tmp = this.getLastInsertError();
let's do this:
`rehash`

- responsibility is only to rehash what values are currently in the buffer
- does not call resize
- returns a value if that value was could not be rehashed

`resize` 

 - responsibility is resize the buffer and copy all values
 - does not call rehash

`_set` 
- returns the value that was unsuccessfully set

`set`
- coordinates rehashing, resizing, and setting
i.e. (really inaccurate pseudocode)
```
if set returns value {
  badvalues.push(value)
  try 3x : rehash
    set(badvalues)
  if failed to rehash 3x, resize and try rehash again
 ...
}
```

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +      this._setValue(pos, lo, hi);
this function writing to webgl texture could potentially cause the slowdowns when rehashing.
we should consider deferring the setvalue until all the rehashing is finished (when we split this file out to texture vs hash)

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +      if (this.loadFactor > 0.5 && this._sizes.level + 1 < Cuckoo._sizeLookup.length) {
we should check for this condition in `set` so we can preemptively resize.  
otherwise if we're at the load factor, we have a high probability of collisions already anyway ( probably will require reshashing a few times first before resize)

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +      if (history.find((el) => { return el.pos === pos && el.hi === hi && el.lo === lo; })) {
We should probably see how often this is occurring. Also, collect statistics on how large history actually gets.
If history is actually very very large, we should consider using a Dictionary instead.

2017-03-09 21:16 UTC, wongwill86 commented on src/babylon/tools/data/CuckooHash.tsx
> +        console.log(`Collision can\'t be resolved! (Load factor: ${this.loadFactor})`);
We should include the history length in the log message.

2017-03-10 23:43 UTC, nkemnitz commented
Think I addressed all issues, except for switching `history` from array to dictionary and delaying texture writes.

2017-03-13 15:59 UTC, wongwill86 approved these changes

2017-03-13 15:59 UTC, merged